//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CeyPASS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bolumler
    {
        public Nullable<int> BolumId { get; set; }
        public Nullable<int> FirmaId { get; set; }
        public string BolumAdi { get; set; }
        public int Id { get; set; }
    }
}
