//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CeyPASS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalismaSekilleri
    {
        public int CalismaSekilId { get; set; }
        public string CalismaSekliAdi { get; set; }
        public System.DateTime BaslangicZaman { get; set; }
        public System.DateTime BitisZaman { get; set; }
        public System.DateTime BaslangicToleransZaman { get; set; }
        public System.DateTime BitisToleransZaman { get; set; }
        public Nullable<System.DateTime> YemekAktiflestirmeZaman { get; set; }
        public Nullable<int> FirmaId { get; set; }
    }
}
