//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CeyPASS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CanliIzlemeHesaplari
    {
        public int KullaniciId { get; set; }
        public int FirmaId { get; set; }
        public string KullaniciAdi { get; set; }
        public byte[] SifreHash { get; set; }
        public string Rol { get; set; }
        public bool AktifMi { get; set; }
        public System.DateTime OlusturmaT { get; set; }
    }
}
