//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CeyPASS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cihazlar
    {
        public int CihazId { get; set; }
        public int FirmaId { get; set; }
        public string CihazAdi { get; set; }
        public string IPAdres { get; set; }
        public int Port { get; set; }
        public bool AktifMi { get; set; }
        public bool BaglandiMi { get; set; }
        public string Notlar { get; set; }
        public byte CihazTipi { get; set; }
        public string CihazModeli { get; set; }
    }
}
