//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CeyPASS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CokluSicilBaglantilari
    {
        public string TCKimlikNo { get; set; }
        public int AnaPersonelId { get; set; }
        public int HedefPersonelId { get; set; }
        public Nullable<int> FirmaId { get; set; }
        public Nullable<int> SirketId { get; set; }
        public Nullable<int> BolumId { get; set; }
        public Nullable<System.DateTime> IseGirisTarihi { get; set; }
        public Nullable<System.DateTime> IstenCikisTarihi { get; set; }
        public int AktarimGunSayisi { get; set; }
        public bool AktifMi { get; set; }
        public string Aciklama { get; set; }
        public System.DateTime OlusturmaZamani { get; set; }
        public int OlusturanKullaniciId { get; set; }
        public Nullable<System.DateTime> GuncellemeZamani { get; set; }
        public Nullable<int> GuncelleyenKullaniciId { get; set; }
    }
}
