//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CeyPASS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinalPuantajVerisi
    {
        public long Id { get; set; }
        public int SicilNo { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public System.DateTime Tarih { get; set; }
        public string CalismaTipi { get; set; }
        public decimal Saat { get; set; }
        public System.DateTime KayitZamani { get; set; }
    }
}
