//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CeyPASS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class IzinTipleri
    {
        public int IzinTipId { get; set; }
        public string Kod { get; set; }
        public string Adi { get; set; }
        public bool UcretliMi { get; set; }
        public bool AktifMi { get; set; }
        public System.DateTime OlusturmaZamani { get; set; }
        public Nullable<System.DateTime> GuncellemeZamani { get; set; }
        public Nullable<bool> SaatlikKullanilabilirMi { get; set; }
    }
}
