//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CeyPASS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class KisiHareketler
    {
        public int Id { get; set; }
        public int FirmaId { get; set; }
        public int CihazId { get; set; }
        public int PersonelId { get; set; }
        public System.DateTime Tarih { get; set; }
        public string Tip { get; set; }
        public System.DateTime KayitZamani { get; set; }
        public bool AktifMi { get; set; }
    }
}
