//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CeyPASS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kisiler
    {
        public string PersonelId { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string KartNo { get; set; }
        public string TcKimlikNo { get; set; }
        public Nullable<int> PozisyonId { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public Nullable<int> DepartmanId { get; set; }
        public Nullable<System.DateTime> IseGirisTarihi { get; set; }
        public Nullable<System.DateTime> IstenCikisTarihi { get; set; }
        public string CalismaStatusu { get; set; }
        public Nullable<int> FirmaId { get; set; }
        public Nullable<int> IsyeriId { get; set; }
        public string CalismaSekli { get; set; }
        public string CepTel { get; set; }
        public byte[] Fotograf { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public string Email { get; set; }
        public Nullable<bool> PuantajYapilirMi { get; set; }
        public Nullable<int> BolumId { get; set; }
    }
}
