//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CeyPASS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class KisiIzinler
    {
        public int KisiIzinId { get; set; }
        public int FirmaId { get; set; }
        public string PersonelId { get; set; }
        public int IzinId { get; set; }
        public System.DateTime Baslangic { get; set; }
        public System.DateTime Bitis { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> OlusturanKullaniciId { get; set; }
        public System.DateTime OlusturmaTarihi { get; set; }
        public Nullable<System.DateTime> GuncellemeTarihi { get; set; }
        public bool AktifMi { get; set; }
        public Nullable<bool> SaatlikIzinMi { get; set; }
        public Nullable<int> SureDakika { get; set; }
    }
}
