//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CeyPASS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciSifreKurtarma
    {
        public int Id { get; set; }
        public int KullaniciId { get; set; }
        public string KurtarmaKodu { get; set; }
        public System.DateTime SonKullanmaZamani { get; set; }
        public bool Kullanildi { get; set; }
    }
}
