//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CeyPASS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PuantajOnay
    {
        public int PersonelId { get; set; }
        public System.DateTime Tarih { get; set; }
        public int OnayDurumu { get; set; }
        public Nullable<int> DuzenlenmisFMDakika { get; set; }
        public string Aciklama { get; set; }
        public System.DateTime OlusturmaZamani { get; set; }
        public Nullable<int> OlusturanKullaniciId { get; set; }
        public Nullable<System.DateTime> GuncellemeZamani { get; set; }
        public Nullable<int> GuncelleyenKullaniciId { get; set; }
    }
}
