//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CeyPASS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PuantajTipleri
    {
        public string Kod { get; set; }
        public string Ad { get; set; }
        public Nullable<decimal> VarsayilanSaat { get; set; }
        public bool AktifMi { get; set; }
        public Nullable<System.DateTime> OlusturmaZamani { get; set; }
    }
}
