//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CeyPASS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PuantajsizKartAtamalari
    {
        public int AtamaId { get; set; }
        public string KartId { get; set; }
        public Nullable<int> AtananPersonelId { get; set; }
        public string MisafirAdSoyad { get; set; }
        public System.DateTime Baslangic { get; set; }
        public Nullable<System.DateTime> Bitis { get; set; }
        public string Notlar { get; set; }
    }
}
