//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CeyPASS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PuantajsizKartlar
    {
        public string KartId { get; set; }
        public string KartNo { get; set; }
        public string KartAdi { get; set; }
        public int FirmaId { get; set; }
        public bool AktifMi { get; set; }
        public string CalismaSekli { get; set; }
        public Nullable<bool> ZiyaretciMi { get; set; }
        public Nullable<bool> AracKartiMi { get; set; }
        public Nullable<bool> TaseronCalisanMi { get; set; }
    }
}
