//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CeyPASS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SistemLoglari
    {
        public int Id { get; set; }
        public System.DateTime LogZamani { get; set; }
        public Nullable<int> KullaniciId { get; set; }
        public string KullaniciAdi { get; set; }
        public byte IslemTuru { get; set; }
        public string Kaynak { get; set; }
        public string Islem { get; set; }
        public string Mesaj { get; set; }
        public string IpAdres { get; set; }
        public string BilgisayarAdi { get; set; }
        public string KorelasyonId { get; set; }
        public string DetayJson { get; set; }
        public string HataMesaji { get; set; }
    }
}
