//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CeyPASS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SistemAyarlar
    {
        public string AyarAdi { get; set; }
        public string AyarDegeri { get; set; }
        public System.DateTime GuncellemeZamani { get; set; }
        public Nullable<int> GuncelleyenId { get; set; }
    }
}
