//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CeyPASS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_YemekhaneEngellenenBekleyenler
    {
        public string PersonelId { get; set; }
        public int CihazId { get; set; }
        public string KartNo { get; set; }
        public string AdSoyad { get; set; }
        public string CalismaSekli { get; set; }
    }
}
