//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CeyPASS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class YemekhaneEngellenenKullanicilar
    {
        public int Id { get; set; }
        public string PersonelId { get; set; }
        public int CihazId { get; set; }
        public string KartNo { get; set; }
        public string AdSoyad { get; set; }
        public Nullable<System.DateTime> EngellemeTarihi { get; set; }
        public Nullable<bool> TekrarEklendiMi { get; set; }
    }
}
