//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CeyPASS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class YemekhaneGirisLimitler
    {
        public int Id { get; set; }
        public string PersonelId { get; set; }
        public Nullable<int> GunlukLimit { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    }
}
