/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all of your component files.
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}", "./App.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        // Web parity tokens (see CeyPASS.Web/Views/Account/Login.cshtml)
        "ceypass-accent": "#b91c1c",
        "ceypass-red-700": "#b91c1c",
        "ceypass-red-600": "#dc2626",
        "ceypass-red-800": "#991b1b",
        "ceypass-text-primary": "#1e293b",
        "ceypass-text-secondary": "#64748b",
        "ceypass-glass-bg": "rgba(255, 255, 255, 0.95)",
        "ceypass-glass-border": "rgba(255, 255, 255, 0.2)",

        "on-primary-fixed": "#410002",
        "error-container": "#93000a",
        "outline-variant": "#5c403c",
        "on-surface": "#dae2fd",
        "on-primary-fixed-variant": "#93000b",
        "outline": "#ac8884",
        "primary-fixed": "#ffdad6",
        "on-secondary-container": "#aeb9d0",
        "tertiary-fixed": "#ffdad6",
        "surface": "#0b1326",
        "on-tertiary": "#690007",
        "on-tertiary-fixed": "#410002",
        "secondary-fixed": "#d8e3fb",
        "on-tertiary-container": "#fff6f4",
        "on-secondary": "#263143",
        "secondary-container": "#3e495d",
        "secondary-fixed-dim": "#bcc7de",
        "inverse-surface": "#dae2fd",
        "on-secondary-fixed": "#111c2d",
        "on-error": "#690005",
        "surface-tint": "#ffb4ab",
        "tertiary-fixed-dim": "#ffb4ac",
        "surface-bright": "#31394d",
        "secondary": "#bcc7de",
        "surface-dim": "#0b1326",
        "surface-variant": "#2d3449",
        "tertiary": "#ffb4ac",
        "primary-container": "#dc2626",
        "error": "#ffb4ab",
        "on-tertiary-fixed-variant": "#8e1214",
        "surface-container-high": "#222a3d",
        "surface-container": "#171f33",
        "on-secondary-fixed-variant": "#3c475a",
        "inverse-on-surface": "#283044",
        "inverse-primary": "#bf0715",
        "on-error-container": "#ffdad6",
        "surface-container-low": "#131b2e",
        "surface-container-lowest": "#060e20",
        "tertiary-container": "#cb403a",
        "on-primary": "#690005",
        "on-surface-variant": "#e6bdb8",
        "primary-fixed-dim": "#ffb4ab",
        "primary": "#ffb4ab",
        "surface-container-highest": "#2d3449",
        "background": "#0b1326",
        "on-primary-container": "#fff6f5",
        "on-background": "#dae2fd"
      },
    },
  },
  plugins: [],
}
