<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>CeyPASS.Tests</RootNamespace>
    <AssemblyName>CeyPASS.Tests</AssemblyName>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);CS8600;CS8601;CS8602;CS8603;CS8618;CS8625</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.2" />
    <PackageReference Include="FluentAssertions" Version="6.12.2" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="8.0.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CeyPASS.Business\CeyPASS.Business.csproj" />
    <ProjectReference Include="..\CeyPASS.DataAccess\CeyPASS.DataAccess.csproj" />
    <ProjectReference Include="..\CeyPASS.Entities\CeyPASS.Entities.csproj" />
    <ProjectReference Include="..\CeyPASS.Infrastructure\CeyPASS.Infrastructure.csproj" />
    <ProjectReference Include="..\CeyPASS.Web\CeyPASS.Web.csproj" />
  </ItemGroup>

</Project>
